kafka:
  replicas: 2

image:
  name: renestadler/kafka-with-ts-plugin:latest

zookeeper:
  replicas: 2

azure:
  container: kafka-data
  account:
    name: clctieredstorage
    key: token
  endpoint: http://clctieredstorage.blob.core.windows.net/