kafka:
    bootstrapServers: ${KAFKA_SERVER:localhost:9092}
    applicationId: data-processing-service
    invoiceTopic: invoice-topic-v1
    invoiceDetailTopic: invoice-audit-log-v1
    customerTopic: customer-topic-v1
    articleTopic: article-topic-v1
    customerStore: customer-store-v1
    articleStore: article-store-v1
management:
    endpoint:
        health:
            group:
                liveness:
                    include: livenessState,kafkaStreams
            probes:
                enabled: true
            show-details: always
            management:
                endpoint:
server:
    port: 80
