## templates/strimzi-kafka-cluster.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.kafka.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: kafka
          image: {{ .Values.kafka.image }}
          imagePullPolicy: {{ .Values.kafka.pullPolicy }}
          env:
            - name: KAFKA_BROKER_ID
              value: "0"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092,BROKER://0.0.0.0:29092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://localhost:9092,BROKER://kafka:29092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,BROKER:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "BROKER"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "2"
            - name: KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "2"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "2"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "false"
            - name: KAFKA_LOG4J_LOGGERS
              value: "io.aiven.kafka.tieredstorage=DEBUG"
            - name: KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS
              value: "10000"
            - name: KAFKA_REMOTE_LOG_STORAGE_SYSTEM_ENABLE
              value: "true"
            - name: KAFKA_REMOTE_LOG_MANAGER_TASK_INTERVAL_MS
              value: "5000"
            - name: KAFKA_REMOTE_LOG_METADATA_MANAGER_CLASS_NAME
              value: "org.apache.kafka.server.log.remote.metadata.storage.TopicBasedRemoteLogMetadataManager"
            - name: KAFKA_REMOTE_LOG_METADATA_MANAGER_LISTENER_NAME
              value: "BROKER"
            - name: KAFKA_RLMM_CONFIG_REMOTE_LOG_METADATA_TOPIC_REPLICATION_FACTOR
              value: "2"
            - name: KAFKA_REMOTE_LOG_STORAGE_MANAGER_CLASS_PATH
              value: "/tiered-storage-for-apache-kafka/core/*:/tiered-storage-for-apache-kafka/azure/*"
            - name: KAFKA_REMOTE_LOG_STORAGE_MANAGER_CLASS_NAME
              value: "io.aiven.kafka.tieredstorage.RemoteStorageManager"
            - name: KAFKA_RSM_CONFIG_CHUNK_SIZE
              value: "4194304" # 4 MiB
            - name: KAFKA_RSM_CONFIG_FETCH_CHUNK_CACHE_CLASS
              value: "io.aiven.kafka.tieredstorage.fetch.cache.DiskChunkCache"
            - name: KAFKA_RSM_CONFIG_FETCH_CHUNK_CACHE_PATH
              value: "/home/appuser/kafka-tiered-storage-cache"
            - name: KAFKA_RSM_CONFIG_FETCH_CHUNK_CACHE_SIZE
              value: "1073741824" # 1 GiB
            - name: KAFKA_RSM_CONFIG_FETCH_CHUNK_CACHE_PREFETCH_MAX_SIZE
              value: "16777216" # 16 MiB
            - name: KAFKA_RSM_CONFIG_CUSTOM_METADATA_FIELDS_INCLUDE
              value: "REMOTE_SIZE"
            - name: KAFKA_RSM_CONFIG_KEY_PREFIX
              value: "tiered-storage-demo/"
            - name: KAFKA_RSM_CONFIG_STORAGE_BACKEND_CLASS
              value: "io.aiven.kafka.tieredstorage.storage.azure.AzureBlobStorage"
            - name: KAFKA_RSM_CONFIG_STORAGE_AZURE_CONTAINER_NAME
              value: {{ .Values.azure.container }}
            - name: KAFKA_RSM_CONFIG_STORAGE_AZURE_ACCOUNT_NAME
              value: {{ .Values.azure.account.name }}
            - name: KAFKA_RSM_CONFIG_STORAGE_AZURE_ACCOUNT_KEY
              value: {{ .Values.azure.account.key }}
            - name: KAFKA_RSM_CONFIG_STORAGE_AZURE_ENDPOINT_URL
              value: {{ .Values.azure.endpoint }}
              value: "http://azurite:10000/devstoreaccount1"
