apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: {{ .Chart.Name }}-zookeeper
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    app: {{ .Chart.Name }}-zookeeper
